---
title: Prophet models
output: html_notebook
---

_Copyright (c) Microsoft Corporation._<br/>
_Licensed under the MIT License._

```{r, echo=FALSE, results="hide", message=FALSE}
library(tidyr)
library(dplyr)
library(tsibble)
library(feasts)
library(fable)
library(prophet)
library(fable.prophet)
```

This notebook builds a forecasting model using the Prophet algorithm.

```{r}
srcdir <- here::here("R_utils")
for(src in dir(srcdir, full.names=TRUE)) source(src)

load_objects("oj_retail", "oj_data.Rdata")
load_objects("oj_retail", "oj_model_basic.Rdata")

cl <- make_cluster(libs=c("tidyr", "dplyr", "fable", "tsibble", "feasts", "prophet", "fable.prophet"))

oj_modelset_pr <- parallel::clusterMap(cl, function(df, basicmod)
{
    df$logmove <- interpolate(select(basicmod, -c(mean, naive, drift)), df)$logmove
    df %>%
        group_by(store, brand) %>%
        fill(deal:maxpricediff, .direction="downup") %>%
        model(
            pr_default=prophet(logmove),
            pr_reg=prophet(logmove ~ deal + feat + price + maxpricediff),
            .safely=FALSE
        )
}, oj_train, oj_modelset_basic)

oj_fcast_pr <- parallel::clusterMap(cl, function(mable, newdata, fcast_func)
{
    newdata <- newdata %>%
        fill(deal:maxpricediff, .direction="downup")
    fcast_func(mable, newdata)
}, oj_modelset_pr, oj_test, MoreArgs=list(fcast_func=get_forecasts))

destroy_cluster(cl)

save_objects(oj_modelset_pr, oj_fcast_pr,
             example="oj_retail", file="oj_model_pr.Rdata")

do.call(rbind, oj_fcast_pr) %>%
    mutate_at(-(1:3), exp) %>%
    eval_forecasts()
```


