# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# To create the conda environment:
# $ conda env create -f environment.yaml
# 
# To update the conda environment:
# $ conda env update -f environment.yaml
#
# To register the conda environment in Jupyter:
# $ conda activate forecasting_env
# $ python -m ipykernel install --user --name forecasting_env

name: forecasting_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - jupyter
  - ipykernel
  - scipy==1.1.0
  - numpy==1.16.2
  - pandas=0.23.4
  - xlrd=1.1.0
  - urllib3=1.21.1
  - scikit-learn=0.20.3
  - pytest
  - papermill>=1.0.1
  - matplotlib=3.1.2
  - r-base
  - r-bayesm
  - pip:
    - black
    - flake8
    - jupytext==1.3.0
    - lightgbm==2.3.0
    - tensorflow==2.0
    - tensorboard==2.1.0
    - nteract-scrapbook==0.3.1
    - gitpython==3.0.8
    - azureml-sdk[explain,automl]==1.0.85
    - statsmodels==0.11.1
    - pmdarima==1.1.1
