name: amlsdkenv

channels:
  - conda-forge

dependencies:

  - python=3.6
  - cython==0.29
  - numpy==1.14.5
  - nb_conda==2.2.1
  - matplotlib==3.0.1 
  - ipykernel  

  - pip:
    #- azure==4.0.0
    - azureml-sdk[notebooks,automl]
    - azureml-dataprep